name: 'Datadog Release Monitors'
description: 'Updates Datadog monitors in accordance with our release contributor alerting'
inputs:
  datadogMonitorTag:
    description: 'The tag of monitors we wish to update based on these rules'
    required: true
  datadogApiKey:
    description: 'Datadog API key used to manage relevant monitors'
    required: true
  datadogAppKey:
    description: 'Datadog Application key used to manage relevant monitors'
    required: true
  alertSlackChannel:
    description: 'The Slack channel we wish to notify about monitors'
    required: true
  contributorOnCallDuration:
    description: 'The total minutes we wish contributors to be notified of related changes after they have been released'
    required: true
  gitHubSlackUserLookup:
    description: 'Lookup JSON object between GitHub username to Slack Memeber Id'
    required: true
  GITHUB_TOKEN:
    description: 'Used to fetch the release upon successful deployment events'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
